// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMrsR8ni7AvfpSa9bfijQg3jzEAwXUQrU',
    appId: '1:439535800522:web:911a25492ee3999f50e433',
    messagingSenderId: '439535800522',
    projectId: 'mediclinic1-99dc0',
    authDomain: 'mediclinic1-99dc0.firebaseapp.com',
    storageBucket: 'mediclinic1-99dc0.firebasestorage.app',
    measurementId: 'G-LQ2GS9XQVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL3TgMBzEB1DPCf7v1-q6ERhQd8KoGQ7Q',
    appId: '1:439535800522:android:e080eb71e4dd647b50e433',
    messagingSenderId: '439535800522',
    projectId: 'mediclinic1-99dc0',
    storageBucket: 'mediclinic1-99dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-2_J3rw-tUQVj51TB7gVmzDn6hC2le8',
    appId: '1:439535800522:ios:813284452916ef2d50e433',
    messagingSenderId: '439535800522',
    projectId: 'mediclinic1-99dc0',
    storageBucket: 'mediclinic1-99dc0.firebasestorage.app',
    iosBundleId: 'com.example.mediclinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7-2_J3rw-tUQVj51TB7gVmzDn6hC2le8',
    appId: '1:439535800522:ios:813284452916ef2d50e433',
    messagingSenderId: '439535800522',
    projectId: 'mediclinic1-99dc0',
    storageBucket: 'mediclinic1-99dc0.firebasestorage.app',
    iosBundleId: 'com.example.mediclinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMrsR8ni7AvfpSa9bfijQg3jzEAwXUQrU',
    appId: '1:439535800522:web:e88137e5d8ac796350e433',
    messagingSenderId: '439535800522',
    projectId: 'mediclinic1-99dc0',
    authDomain: 'mediclinic1-99dc0.firebaseapp.com',
    storageBucket: 'mediclinic1-99dc0.firebasestorage.app',
    measurementId: 'G-8YNHCNPJZN',
  );
}
