name: igabay_care_mobile
description: "IgabayCare Mobile - Healthcare Clinic Management Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase dependencies
  supabase_flutter: ^2.5.6
  
  # State management
  provider: ^6.1.2
  
  # UI and navigation
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  
  # HTTP and networking
  http: ^1.2.2
  
  # Local storage
  shared_preferences: ^2.2.3
  
  # Date and time
  intl: ^0.19.0
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  
  # Forms and validation
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  
  # Location services
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  
  # Maps
  google_maps_flutter: ^2.6.1
  
  # Push notifications
  firebase_messaging: ^15.0.4
  firebase_core: ^3.3.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Utils
  uuid: ^4.4.0
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700